// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$841 {

    static final FunctionDescriptor PFNGLEXECUTEPROGRAMNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLEXECUTEPROGRAMNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$841.PFNGLEXECUTEPROGRAMNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGENPROGRAMSNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGENPROGRAMSNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$841.PFNGLGENPROGRAMSNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETPROGRAMPARAMETERDVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETPROGRAMPARAMETERDVNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$841.PFNGLGETPROGRAMPARAMETERDVNVPROC$FUNC, false
    );
}


