// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$207 {

    static final FunctionDescriptor PFNGLDRAWELEMENTSINDIRECTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLDRAWELEMENTSINDIRECTPROC$MH = RuntimeHelper.downcallHandle(
        constants$207.PFNGLDRAWELEMENTSINDIRECTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORM1DPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle PFNGLUNIFORM1DPROC$MH = RuntimeHelper.downcallHandle(
        constants$207.PFNGLUNIFORM1DPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORM2DPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle PFNGLUNIFORM2DPROC$MH = RuntimeHelper.downcallHandle(
        constants$207.PFNGLUNIFORM2DPROC$FUNC, false
    );
}


