// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$899 {

    static final FunctionDescriptor PFNGLGETCOLORTABLESGIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETCOLORTABLESGIPROC$MH = RuntimeHelper.downcallHandle(
        constants$899.PFNGLGETCOLORTABLESGIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETCOLORTABLEPARAMETERFVSGIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETCOLORTABLEPARAMETERFVSGIPROC$MH = RuntimeHelper.downcallHandle(
        constants$899.PFNGLGETCOLORTABLEPARAMETERFVSGIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETCOLORTABLEPARAMETERIVSGIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETCOLORTABLEPARAMETERIVSGIPROC$MH = RuntimeHelper.downcallHandle(
        constants$899.PFNGLGETCOLORTABLEPARAMETERIVSGIPROC$FUNC, false
    );
}


