// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$591 {

    static final FunctionDescriptor PFNGLDISABLECLIENTSTATEIEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLDISABLECLIENTSTATEIEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$591.PFNGLDISABLECLIENTSTATEIEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETFLOATI_VEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETFLOATI_VEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$591.PFNGLGETFLOATI_VEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETDOUBLEI_VEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETDOUBLEI_VEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$591.PFNGLGETDOUBLEI_VEXTPROC$FUNC, false
    );
}


