// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$895 {

    static final FunctionDescriptor PFNGLDEFORMSGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLDEFORMSGIXPROC$MH = RuntimeHelper.downcallHandle(
        constants$895.PFNGLDEFORMSGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLLOADIDENTITYDEFORMATIONMAPSGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLLOADIDENTITYDEFORMATIONMAPSGIXPROC$MH = RuntimeHelper.downcallHandle(
        constants$895.PFNGLLOADIDENTITYDEFORMATIONMAPSGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLREFERENCEPLANESGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLREFERENCEPLANESGIXPROC$MH = RuntimeHelper.downcallHandle(
        constants$895.PFNGLREFERENCEPLANESGIXPROC$FUNC, false
    );
}


