// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$8 {

    static final FunctionDescriptor glAccum$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle glAccum$MH = RuntimeHelper.downcallHandle(
        "glAccum",
        constants$8.glAccum$FUNC, false
    );
    static final FunctionDescriptor glMatrixMode$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle glMatrixMode$MH = RuntimeHelper.downcallHandle(
        "glMatrixMode",
        constants$8.glMatrixMode$FUNC, false
    );
    static final FunctionDescriptor glOrtho$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle glOrtho$MH = RuntimeHelper.downcallHandle(
        "glOrtho",
        constants$8.glOrtho$FUNC, false
    );
    static final FunctionDescriptor glFrustum$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle glFrustum$MH = RuntimeHelper.downcallHandle(
        "glFrustum",
        constants$8.glFrustum$FUNC, false
    );
    static final FunctionDescriptor glViewport$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle glViewport$MH = RuntimeHelper.downcallHandle(
        "glViewport",
        constants$8.glViewport$FUNC, false
    );
    static final FunctionDescriptor glPushMatrix$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle glPushMatrix$MH = RuntimeHelper.downcallHandle(
        "glPushMatrix",
        constants$8.glPushMatrix$FUNC, false
    );
}


