// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$643 {

    static final FunctionDescriptor PFNGLCREATEMEMORYOBJECTSEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLCREATEMEMORYOBJECTSEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$643.PFNGLCREATEMEMORYOBJECTSEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMEMORYOBJECTPARAMETERIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLMEMORYOBJECTPARAMETERIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$643.PFNGLMEMORYOBJECTPARAMETERIVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETMEMORYOBJECTPARAMETERIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETMEMORYOBJECTPARAMETERIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$643.PFNGLGETMEMORYOBJECTPARAMETERIVEXTPROC$FUNC, false
    );
}


