// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$558 {

    static final FunctionDescriptor PFNGLCOPYMULTITEXIMAGE2DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLCOPYMULTITEXIMAGE2DEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$558.PFNGLCOPYMULTITEXIMAGE2DEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOPYMULTITEXSUBIMAGE1DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLCOPYMULTITEXSUBIMAGE1DEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$558.PFNGLCOPYMULTITEXSUBIMAGE1DEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOPYMULTITEXSUBIMAGE2DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLCOPYMULTITEXSUBIMAGE2DEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$558.PFNGLCOPYMULTITEXSUBIMAGE2DEXTPROC$FUNC, false
    );
}


