// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$526 {

    static final FunctionDescriptor PFNGLTANGENT3DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle PFNGLTANGENT3DEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$526.PFNGLTANGENT3DEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTANGENT3DVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLTANGENT3DVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$526.PFNGLTANGENT3DVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTANGENT3FEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle PFNGLTANGENT3FEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$526.PFNGLTANGENT3FEXTPROC$FUNC, false
    );
}


