// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$758 {

    static final FunctionDescriptor PFNGLPROGRAMENVPARAMETERI4UINVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMENVPARAMETERI4UINVPROC$MH = RuntimeHelper.downcallHandle(
        constants$758.PFNGLPROGRAMENVPARAMETERI4UINVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMENVPARAMETERI4UIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMENVPARAMETERI4UIVNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$758.PFNGLPROGRAMENVPARAMETERI4UIVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMENVPARAMETERSI4UIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMENVPARAMETERSI4UIVNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$758.PFNGLPROGRAMENVPARAMETERSI4UIVNVPROC$FUNC, false
    );
}


