// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$865 {

    static final FunctionDescriptor PFNGLVERTEXATTRIBI4IVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBI4IVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$865.PFNGLVERTEXATTRIBI4IVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBI1UIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBI1UIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$865.PFNGLVERTEXATTRIBI1UIVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBI2UIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBI2UIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$865.PFNGLVERTEXATTRIBI2UIVEXTPROC$FUNC, false
    );
}


