// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$748 {

    static final FunctionDescriptor PFNGLGETPROGRAMNAMEDPARAMETERFVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETPROGRAMNAMEDPARAMETERFVNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$748.PFNGLGETPROGRAMNAMEDPARAMETERFVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETPROGRAMNAMEDPARAMETERDVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETPROGRAMNAMEDPARAMETERDVNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$748.PFNGLGETPROGRAMNAMEDPARAMETERDVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOVERAGEMODULATIONTABLENVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLCOVERAGEMODULATIONTABLENVPROC$MH = RuntimeHelper.downcallHandle(
        constants$748.PFNGLCOVERAGEMODULATIONTABLENVPROC$FUNC, false
    );
}


