// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$175 {

    static final FunctionDescriptor PFNGLTEXBUFFERPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLTEXBUFFERPROC$MH = RuntimeHelper.downcallHandle(
        constants$175.PFNGLTEXBUFFERPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPRIMITIVERESTARTINDEXPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLPRIMITIVERESTARTINDEXPROC$MH = RuntimeHelper.downcallHandle(
        constants$175.PFNGLPRIMITIVERESTARTINDEXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOPYBUFFERSUBDATAPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle PFNGLCOPYBUFFERSUBDATAPROC$MH = RuntimeHelper.downcallHandle(
        constants$175.PFNGLCOPYBUFFERSUBDATAPROC$FUNC, false
    );
}


