// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$677 {

    static final FunctionDescriptor PFNGLCOLORPOINTEREXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLCOLORPOINTEREXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$677.PFNGLCOLORPOINTEREXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDRAWARRAYSEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLDRAWARRAYSEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$677.PFNGLDRAWARRAYSEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLEDGEFLAGPOINTEREXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLEDGEFLAGPOINTEREXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$677.PFNGLEDGEFLAGPOINTEREXTPROC$FUNC, false
    );
}


