// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$555 {

    static final FunctionDescriptor PFNGLMULTITEXPARAMETERIEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLMULTITEXPARAMETERIEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$555.PFNGLMULTITEXPARAMETERIEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTITEXPARAMETERIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLMULTITEXPARAMETERIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$555.PFNGLMULTITEXPARAMETERIVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTITEXPARAMETERFEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle PFNGLMULTITEXPARAMETERFEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$555.PFNGLMULTITEXPARAMETERFEXTPROC$FUNC, false
    );
}


