// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$925 {

    static final FunctionDescriptor gluNewQuadric$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gluNewQuadric$MH = RuntimeHelper.downcallHandle(
        "gluNewQuadric",
        constants$925.gluNewQuadric$FUNC, false
    );
    static final FunctionDescriptor gluNewTess$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gluNewTess$MH = RuntimeHelper.downcallHandle(
        "gluNewTess",
        constants$925.gluNewTess$FUNC, false
    );
    static final FunctionDescriptor gluNextContour$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gluNextContour$MH = RuntimeHelper.downcallHandle(
        "gluNextContour",
        constants$925.gluNextContour$FUNC, false
    );
    static final FunctionDescriptor gluNurbsCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gluNurbsCallback$MH = RuntimeHelper.downcallHandle(
        "gluNurbsCallback",
        constants$925.gluNurbsCallback$FUNC, false
    );
    static final FunctionDescriptor gluNurbsCallbackData$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gluNurbsCallbackData$MH = RuntimeHelper.downcallHandle(
        "gluNurbsCallbackData",
        constants$925.gluNurbsCallbackData$FUNC, false
    );
    static final FunctionDescriptor gluNurbsCallbackDataEXT$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gluNurbsCallbackDataEXT$MH = RuntimeHelper.downcallHandle(
        "gluNurbsCallbackDataEXT",
        constants$925.gluNurbsCallbackDataEXT$FUNC, false
    );
}


