// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$528 {

    static final FunctionDescriptor PFNGLTANGENT3SEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle PFNGLTANGENT3SEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$528.PFNGLTANGENT3SEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTANGENT3SVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLTANGENT3SVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$528.PFNGLTANGENT3SVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBINORMAL3BEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle PFNGLBINORMAL3BEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$528.PFNGLBINORMAL3BEXTPROC$FUNC, false
    );
}


