// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$113 {

    static final FunctionDescriptor PFNGLGETBUFFERPOINTERVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETBUFFERPOINTERVPROC$MH = RuntimeHelper.downcallHandle(
        constants$113.PFNGLGETBUFFERPOINTERVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBLENDEQUATIONSEPARATEPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLBLENDEQUATIONSEPARATEPROC$MH = RuntimeHelper.downcallHandle(
        constants$113.PFNGLBLENDEQUATIONSEPARATEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDRAWBUFFERSPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLDRAWBUFFERSPROC$MH = RuntimeHelper.downcallHandle(
        constants$113.PFNGLDRAWBUFFERSPROC$FUNC, false
    );
}


