// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$838 {

    static final FunctionDescriptor PFNGLEDGEFLAGFORMATNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLEDGEFLAGFORMATNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$838.PFNGLEDGEFLAGFORMATNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSECONDARYCOLORFORMATNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLSECONDARYCOLORFORMATNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$838.PFNGLSECONDARYCOLORFORMATNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFOGCOORDFORMATNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLFOGCOORDFORMATNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$838.PFNGLFOGCOORDFORMATNVPROC$FUNC, false
    );
}


