// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$104 {

    static final FunctionDescriptor PFNGLWINDOWPOS3DVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLWINDOWPOS3DVPROC$MH = RuntimeHelper.downcallHandle(
        constants$104.PFNGLWINDOWPOS3DVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLWINDOWPOS3FPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle PFNGLWINDOWPOS3FPROC$MH = RuntimeHelper.downcallHandle(
        constants$104.PFNGLWINDOWPOS3FPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLWINDOWPOS3FVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLWINDOWPOS3FVPROC$MH = RuntimeHelper.downcallHandle(
        constants$104.PFNGLWINDOWPOS3FVPROC$FUNC, false
    );
}


