// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$131 {

    static final FunctionDescriptor PFNGLUNIFORMMATRIX3FVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLUNIFORMMATRIX3FVPROC$MH = RuntimeHelper.downcallHandle(
        constants$131.PFNGLUNIFORMMATRIX3FVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORMMATRIX4FVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLUNIFORMMATRIX4FVPROC$MH = RuntimeHelper.downcallHandle(
        constants$131.PFNGLUNIFORMMATRIX4FVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVALIDATEPROGRAMPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLVALIDATEPROGRAMPROC$MH = RuntimeHelper.downcallHandle(
        constants$131.PFNGLVALIDATEPROGRAMPROC$FUNC, false
    );
}


