// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$60 {

    static final FunctionDescriptor glResetHistogram$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle glResetHistogram$MH = RuntimeHelper.downcallHandle(
        "glResetHistogram",
        constants$60.glResetHistogram$FUNC, false
    );
    static final FunctionDescriptor glGetHistogram$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glGetHistogram$MH = RuntimeHelper.downcallHandle(
        "glGetHistogram",
        constants$60.glGetHistogram$FUNC, false
    );
    static final FunctionDescriptor glGetHistogramParameterfv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glGetHistogramParameterfv$MH = RuntimeHelper.downcallHandle(
        "glGetHistogramParameterfv",
        constants$60.glGetHistogramParameterfv$FUNC, false
    );
    static final FunctionDescriptor glGetHistogramParameteriv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glGetHistogramParameteriv$MH = RuntimeHelper.downcallHandle(
        "glGetHistogramParameteriv",
        constants$60.glGetHistogramParameteriv$FUNC, false
    );
    static final FunctionDescriptor glMinmax$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle glMinmax$MH = RuntimeHelper.downcallHandle(
        "glMinmax",
        constants$60.glMinmax$FUNC, false
    );
    static final FunctionDescriptor glResetMinmax$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle glResetMinmax$MH = RuntimeHelper.downcallHandle(
        "glResetMinmax",
        constants$60.glResetMinmax$FUNC, false
    );
}


