// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$293 {

    static final FunctionDescriptor PFNGLTEXTUREPARAMETERIUIVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLTEXTUREPARAMETERIUIVPROC$MH = RuntimeHelper.downcallHandle(
        constants$293.PFNGLTEXTUREPARAMETERIUIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTUREPARAMETERIVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLTEXTUREPARAMETERIVPROC$MH = RuntimeHelper.downcallHandle(
        constants$293.PFNGLTEXTUREPARAMETERIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGENERATETEXTUREMIPMAPPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLGENERATETEXTUREMIPMAPPROC$MH = RuntimeHelper.downcallHandle(
        constants$293.PFNGLGENERATETEXTUREMIPMAPPROC$FUNC, false
    );
}


