// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$762 {

    static final FunctionDescriptor PFNGLVERTEX3HVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEX3HVNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$762.PFNGLVERTEX3HVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEX4HNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle PFNGLVERTEX4HNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$762.PFNGLVERTEX4HNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEX4HVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEX4HVNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$762.PFNGLVERTEX4HVNVPROC$FUNC, false
    );
}


