// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$500 {

    static final FunctionDescriptor PFNGLGETVARIANTARRAYOBJECTFVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETVARIANTARRAYOBJECTFVATIPROC$MH = RuntimeHelper.downcallHandle(
        constants$500.PFNGLGETVARIANTARRAYOBJECTFVATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETVARIANTARRAYOBJECTIVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETVARIANTARRAYOBJECTIVATIPROC$MH = RuntimeHelper.downcallHandle(
        constants$500.PFNGLGETVARIANTARRAYOBJECTIVATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBARRAYOBJECTATIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBARRAYOBJECTATIPROC$MH = RuntimeHelper.downcallHandle(
        constants$500.PFNGLVERTEXATTRIBARRAYOBJECTATIPROC$FUNC, false
    );
}


