// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$267 {

    static final FunctionDescriptor PFNGLOBJECTLABELPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLOBJECTLABELPROC$MH = RuntimeHelper.downcallHandle(
        constants$267.PFNGLOBJECTLABELPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETOBJECTLABELPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETOBJECTLABELPROC$MH = RuntimeHelper.downcallHandle(
        constants$267.PFNGLGETOBJECTLABELPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLOBJECTPTRLABELPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLOBJECTPTRLABELPROC$MH = RuntimeHelper.downcallHandle(
        constants$267.PFNGLOBJECTPTRLABELPROC$FUNC, false
    );
}


