// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$278 {

    static final FunctionDescriptor PFNGLGETNAMEDBUFFERPOINTERVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETNAMEDBUFFERPOINTERVPROC$MH = RuntimeHelper.downcallHandle(
        constants$278.PFNGLGETNAMEDBUFFERPOINTERVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETNAMEDBUFFERSUBDATAPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETNAMEDBUFFERSUBDATAPROC$MH = RuntimeHelper.downcallHandle(
        constants$278.PFNGLGETNAMEDBUFFERSUBDATAPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCREATEFRAMEBUFFERSPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLCREATEFRAMEBUFFERSPROC$MH = RuntimeHelper.downcallHandle(
        constants$278.PFNGLCREATEFRAMEBUFFERSPROC$FUNC, false
    );
}


