// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$317 {

    static final FunctionDescriptor PFNGLPROGRAMUNIFORMHANDLEUI64VARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMUNIFORMHANDLEUI64VARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$317.PFNGLPROGRAMUNIFORMHANDLEUI64VARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISTEXTUREHANDLERESIDENTARBPROC$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle PFNGLISTEXTUREHANDLERESIDENTARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$317.PFNGLISTEXTUREHANDLERESIDENTARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISIMAGEHANDLERESIDENTARBPROC$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle PFNGLISIMAGEHANDLERESIDENTARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$317.PFNGLISIMAGEHANDLERESIDENTARBPROC$FUNC, false
    );
}


