// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$4 {

    static final FunctionDescriptor glEnable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle glEnable$MH = RuntimeHelper.downcallHandle(
        "glEnable",
        constants$4.glEnable$FUNC, false
    );
    static final FunctionDescriptor glDisable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle glDisable$MH = RuntimeHelper.downcallHandle(
        "glDisable",
        constants$4.glDisable$FUNC, false
    );
    static final FunctionDescriptor glIsEnabled$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle glIsEnabled$MH = RuntimeHelper.downcallHandle(
        "glIsEnabled",
        constants$4.glIsEnabled$FUNC, false
    );
    static final FunctionDescriptor glEnableClientState$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle glEnableClientState$MH = RuntimeHelper.downcallHandle(
        "glEnableClientState",
        constants$4.glEnableClientState$FUNC, false
    );
    static final FunctionDescriptor glDisableClientState$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle glDisableClientState$MH = RuntimeHelper.downcallHandle(
        "glDisableClientState",
        constants$4.glDisableClientState$FUNC, false
    );
    static final FunctionDescriptor glGetBooleanv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glGetBooleanv$MH = RuntimeHelper.downcallHandle(
        "glGetBooleanv",
        constants$4.glGetBooleanv$FUNC, false
    );
}


