// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$312 {

    static final FunctionDescriptor PFNGLSPECIALIZESHADERPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLSPECIALIZESHADERPROC$MH = RuntimeHelper.downcallHandle(
        constants$312.PFNGLSPECIALIZESHADERPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC$MH = RuntimeHelper.downcallHandle(
        constants$312.PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC$MH = RuntimeHelper.downcallHandle(
        constants$312.PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC$FUNC, false
    );
}


