// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$704 {

    static final FunctionDescriptor PFNGLFOGCOORDPOINTERLISTIBMPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLFOGCOORDPOINTERLISTIBMPROC$MH = RuntimeHelper.downcallHandle(
        constants$704.PFNGLFOGCOORDPOINTERLISTIBMPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLINDEXPOINTERLISTIBMPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLINDEXPOINTERLISTIBMPROC$MH = RuntimeHelper.downcallHandle(
        constants$704.PFNGLINDEXPOINTERLISTIBMPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLNORMALPOINTERLISTIBMPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLNORMALPOINTERLISTIBMPROC$MH = RuntimeHelper.downcallHandle(
        constants$704.PFNGLNORMALPOINTERLISTIBMPROC$FUNC, false
    );
}


