// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$42 {

    static final FunctionDescriptor glPixelMapusv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glPixelMapusv$MH = RuntimeHelper.downcallHandle(
        "glPixelMapusv",
        constants$42.glPixelMapusv$FUNC, false
    );
    static final FunctionDescriptor glGetPixelMapfv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glGetPixelMapfv$MH = RuntimeHelper.downcallHandle(
        "glGetPixelMapfv",
        constants$42.glGetPixelMapfv$FUNC, false
    );
    static final FunctionDescriptor glGetPixelMapuiv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glGetPixelMapuiv$MH = RuntimeHelper.downcallHandle(
        "glGetPixelMapuiv",
        constants$42.glGetPixelMapuiv$FUNC, false
    );
    static final FunctionDescriptor glGetPixelMapusv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glGetPixelMapusv$MH = RuntimeHelper.downcallHandle(
        "glGetPixelMapusv",
        constants$42.glGetPixelMapusv$FUNC, false
    );
    static final FunctionDescriptor glBitmap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glBitmap$MH = RuntimeHelper.downcallHandle(
        "glBitmap",
        constants$42.glBitmap$FUNC, false
    );
    static final FunctionDescriptor glReadPixels$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glReadPixels$MH = RuntimeHelper.downcallHandle(
        "glReadPixels",
        constants$42.glReadPixels$FUNC, false
    );
}


