// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$543 {

    static final FunctionDescriptor PFNGLTEXTUREPARAMETERFVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLTEXTUREPARAMETERFVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$543.PFNGLTEXTUREPARAMETERFVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTUREPARAMETERIEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLTEXTUREPARAMETERIEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$543.PFNGLTEXTUREPARAMETERIEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTUREPARAMETERIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLTEXTUREPARAMETERIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$543.PFNGLTEXTUREPARAMETERIVEXTPROC$FUNC, false
    );
}


