// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$103 {

    static final FunctionDescriptor PFNGLWINDOWPOS2SPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle PFNGLWINDOWPOS2SPROC$MH = RuntimeHelper.downcallHandle(
        constants$103.PFNGLWINDOWPOS2SPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLWINDOWPOS2SVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLWINDOWPOS2SVPROC$MH = RuntimeHelper.downcallHandle(
        constants$103.PFNGLWINDOWPOS2SVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLWINDOWPOS3DPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle PFNGLWINDOWPOS3DPROC$MH = RuntimeHelper.downcallHandle(
        constants$103.PFNGLWINDOWPOS3DPROC$FUNC, false
    );
}


