// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$570 {

    static final FunctionDescriptor PFNGLMATRIXLOADTRANSPOSEDEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLMATRIXLOADTRANSPOSEDEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$570.PFNGLMATRIXLOADTRANSPOSEDEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMATRIXMULTTRANSPOSEFEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLMATRIXMULTTRANSPOSEFEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$570.PFNGLMATRIXMULTTRANSPOSEFEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMATRIXMULTTRANSPOSEDEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLMATRIXMULTTRANSPOSEDEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$570.PFNGLMATRIXMULTTRANSPOSEDEXTPROC$FUNC, false
    );
}


