// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$389 {

    static final FunctionDescriptor PFNGLVERTEXATTRIB2FVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIB2FVARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$389.PFNGLVERTEXATTRIB2FVARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIB2SARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIB2SARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$389.PFNGLVERTEXATTRIB2SARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIB2SVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIB2SVARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$389.PFNGLVERTEXATTRIB2SVARBPROC$FUNC, false
    );
}


