// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$240 {

    static final FunctionDescriptor PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC$MH = RuntimeHelper.downcallHandle(
        constants$240.PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC$MH = RuntimeHelper.downcallHandle(
        constants$240.PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC$MH = RuntimeHelper.downcallHandle(
        constants$240.PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC$FUNC, false
    );
}


