// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$52 {

    static final FunctionDescriptor glEvalCoord1fv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glEvalCoord1fv$MH = RuntimeHelper.downcallHandle(
        "glEvalCoord1fv",
        constants$52.glEvalCoord1fv$FUNC, false
    );
    static final FunctionDescriptor glEvalCoord2d$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle glEvalCoord2d$MH = RuntimeHelper.downcallHandle(
        "glEvalCoord2d",
        constants$52.glEvalCoord2d$FUNC, false
    );
    static final FunctionDescriptor glEvalCoord2f$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle glEvalCoord2f$MH = RuntimeHelper.downcallHandle(
        "glEvalCoord2f",
        constants$52.glEvalCoord2f$FUNC, false
    );
    static final FunctionDescriptor glEvalCoord2dv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glEvalCoord2dv$MH = RuntimeHelper.downcallHandle(
        "glEvalCoord2dv",
        constants$52.glEvalCoord2dv$FUNC, false
    );
    static final FunctionDescriptor glEvalCoord2fv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glEvalCoord2fv$MH = RuntimeHelper.downcallHandle(
        "glEvalCoord2fv",
        constants$52.glEvalCoord2fv$FUNC, false
    );
    static final FunctionDescriptor glMapGrid1d$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle glMapGrid1d$MH = RuntimeHelper.downcallHandle(
        "glMapGrid1d",
        constants$52.glMapGrid1d$FUNC, false
    );
}


