// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$765 {

    static final FunctionDescriptor PFNGLTEXCOORD1HNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle PFNGLTEXCOORD1HNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$765.PFNGLTEXCOORD1HNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXCOORD1HVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLTEXCOORD1HVNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$765.PFNGLTEXCOORD1HVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXCOORD2HNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle PFNGLTEXCOORD2HNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$765.PFNGLTEXCOORD2HNVPROC$FUNC, false
    );
}


