// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$346 {

    static final FunctionDescriptor PFNGLMATRIXINDEXUIVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLMATRIXINDEXUIVARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$346.PFNGLMATRIXINDEXUIVARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMATRIXINDEXPOINTERARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLMATRIXINDEXPOINTERARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$346.PFNGLMATRIXINDEXPOINTERARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSAMPLECOVERAGEARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle PFNGLSAMPLECOVERAGEARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$346.PFNGLSAMPLECOVERAGEARBPROC$FUNC, false
    );
}


