// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$261 {

    static final FunctionDescriptor PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC$MH = RuntimeHelper.downcallHandle(
        constants$261.PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSHADERSTORAGEBLOCKBINDINGPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLSHADERSTORAGEBLOCKBINDINGPROC$MH = RuntimeHelper.downcallHandle(
        constants$261.PFNGLSHADERSTORAGEBLOCKBINDINGPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXBUFFERRANGEPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle PFNGLTEXBUFFERRANGEPROC$MH = RuntimeHelper.downcallHandle(
        constants$261.PFNGLTEXBUFFERRANGEPROC$FUNC, false
    );
}


