// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$259 {

    static final FunctionDescriptor PFNGLMULTIDRAWELEMENTSINDIRECTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLMULTIDRAWELEMENTSINDIRECTPROC$MH = RuntimeHelper.downcallHandle(
        constants$259.PFNGLMULTIDRAWELEMENTSINDIRECTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETPROGRAMINTERFACEIVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETPROGRAMINTERFACEIVPROC$MH = RuntimeHelper.downcallHandle(
        constants$259.PFNGLGETPROGRAMINTERFACEIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETPROGRAMRESOURCEINDEXPROC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETPROGRAMRESOURCEINDEXPROC$MH = RuntimeHelper.downcallHandle(
        constants$259.PFNGLGETPROGRAMRESOURCEINDEXPROC$FUNC, false
    );
}


