// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$700 {

    static final FunctionDescriptor PFNGLIMAGETRANSFORMPARAMETERIHPPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLIMAGETRANSFORMPARAMETERIHPPROC$MH = RuntimeHelper.downcallHandle(
        constants$700.PFNGLIMAGETRANSFORMPARAMETERIHPPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLIMAGETRANSFORMPARAMETERFHPPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle PFNGLIMAGETRANSFORMPARAMETERFHPPROC$MH = RuntimeHelper.downcallHandle(
        constants$700.PFNGLIMAGETRANSFORMPARAMETERFHPPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLIMAGETRANSFORMPARAMETERIVHPPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLIMAGETRANSFORMPARAMETERIVHPPROC$MH = RuntimeHelper.downcallHandle(
        constants$700.PFNGLIMAGETRANSFORMPARAMETERIVHPPROC$FUNC, false
    );
}


