// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$697 {

    static final FunctionDescriptor PFNGLVERTEXWEIGHTFEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXWEIGHTFEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$697.PFNGLVERTEXWEIGHTFEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXWEIGHTFVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXWEIGHTFVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$697.PFNGLVERTEXWEIGHTFVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXWEIGHTPOINTEREXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXWEIGHTPOINTEREXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$697.PFNGLVERTEXWEIGHTPOINTEREXTPROC$FUNC, false
    );
}


