// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$780 {

    static final FunctionDescriptor PFNGLGENPATHSNVPROC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLGENPATHSNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$780.PFNGLGENPATHSNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDELETEPATHSNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLDELETEPATHSNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$780.PFNGLDELETEPATHSNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISPATHNVPROC$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLISPATHNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$780.PFNGLISPATHNVPROC$FUNC, false
    );
}


