// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$244 {

    static final FunctionDescriptor PFNGLVERTEXATTRIBL4DPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBL4DPROC$MH = RuntimeHelper.downcallHandle(
        constants$244.PFNGLVERTEXATTRIBL4DPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBL1DVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBL1DVPROC$MH = RuntimeHelper.downcallHandle(
        constants$244.PFNGLVERTEXATTRIBL1DVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBL2DVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBL2DVPROC$MH = RuntimeHelper.downcallHandle(
        constants$244.PFNGLVERTEXATTRIBL2DVPROC$FUNC, false
    );
}


