// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$220 {

    static final FunctionDescriptor PFNGLGETQUERYINDEXEDIVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETQUERYINDEXEDIVPROC$MH = RuntimeHelper.downcallHandle(
        constants$220.PFNGLGETQUERYINDEXEDIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLRELEASESHADERCOMPILERPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLRELEASESHADERCOMPILERPROC$MH = RuntimeHelper.downcallHandle(
        constants$220.PFNGLRELEASESHADERCOMPILERPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSHADERBINARYPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLSHADERBINARYPROC$MH = RuntimeHelper.downcallHandle(
        constants$220.PFNGLSHADERBINARYPROC$FUNC, false
    );
}


