// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$702 {

    static final FunctionDescriptor PFNGLMULTIMODEDRAWARRAYSIBMPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLMULTIMODEDRAWARRAYSIBMPROC$MH = RuntimeHelper.downcallHandle(
        constants$702.PFNGLMULTIMODEDRAWARRAYSIBMPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTIMODEDRAWELEMENTSIBMPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLMULTIMODEDRAWELEMENTSIBMPROC$MH = RuntimeHelper.downcallHandle(
        constants$702.PFNGLMULTIMODEDRAWELEMENTSIBMPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFLUSHSTATICDATAIBMPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLFLUSHSTATICDATAIBMPROC$MH = RuntimeHelper.downcallHandle(
        constants$702.PFNGLFLUSHSTATICDATAIBMPROC$FUNC, false
    );
}


