// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$480 {

    static final FunctionDescriptor PFNGLFINISHOBJECTAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLFINISHOBJECTAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        constants$480.PFNGLFINISHOBJECTAPPLEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBUFFERPARAMETERIAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLBUFFERPARAMETERIAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        constants$480.PFNGLBUFFERPARAMETERIAPPLEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFLUSHMAPPEDBUFFERRANGEAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle PFNGLFLUSHMAPPEDBUFFERRANGEAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        constants$480.PFNGLFLUSHMAPPEDBUFFERRANGEAPPLEPROC$FUNC, false
    );
}


