// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$927 {

    static final FunctionDescriptor gluPickMatrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gluPickMatrix$MH = RuntimeHelper.downcallHandle(
        "gluPickMatrix",
        constants$927.gluPickMatrix$FUNC, false
    );
    static final FunctionDescriptor gluProject$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gluProject$MH = RuntimeHelper.downcallHandle(
        "gluProject",
        constants$927.gluProject$FUNC, false
    );
    static final FunctionDescriptor gluPwlCurve$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gluPwlCurve$MH = RuntimeHelper.downcallHandle(
        "gluPwlCurve",
        constants$927.gluPwlCurve$FUNC, false
    );
    static final FunctionDescriptor gluQuadricCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gluQuadricCallback$MH = RuntimeHelper.downcallHandle(
        "gluQuadricCallback",
        constants$927.gluQuadricCallback$FUNC, false
    );
    static final FunctionDescriptor gluQuadricDrawStyle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gluQuadricDrawStyle$MH = RuntimeHelper.downcallHandle(
        "gluQuadricDrawStyle",
        constants$927.gluQuadricDrawStyle$FUNC, false
    );
    static final FunctionDescriptor gluQuadricNormals$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gluQuadricNormals$MH = RuntimeHelper.downcallHandle(
        "gluQuadricNormals",
        constants$927.gluQuadricNormals$FUNC, false
    );
}


