// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$38 {

    static final FunctionDescriptor glLightf$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle glLightf$MH = RuntimeHelper.downcallHandle(
        "glLightf",
        constants$38.glLightf$FUNC, false
    );
    static final FunctionDescriptor glLighti$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle glLighti$MH = RuntimeHelper.downcallHandle(
        "glLighti",
        constants$38.glLighti$FUNC, false
    );
    static final FunctionDescriptor glLightfv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glLightfv$MH = RuntimeHelper.downcallHandle(
        "glLightfv",
        constants$38.glLightfv$FUNC, false
    );
    static final FunctionDescriptor glLightiv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glLightiv$MH = RuntimeHelper.downcallHandle(
        "glLightiv",
        constants$38.glLightiv$FUNC, false
    );
    static final FunctionDescriptor glGetLightfv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glGetLightfv$MH = RuntimeHelper.downcallHandle(
        "glGetLightfv",
        constants$38.glGetLightfv$FUNC, false
    );
    static final FunctionDescriptor glGetLightiv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glGetLightiv$MH = RuntimeHelper.downcallHandle(
        "glGetLightiv",
        constants$38.glGetLightiv$FUNC, false
    );
}


