// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$763 {

    static final FunctionDescriptor PFNGLNORMAL3HNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle PFNGLNORMAL3HNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$763.PFNGLNORMAL3HNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLNORMAL3HVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLNORMAL3HVNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$763.PFNGLNORMAL3HVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOLOR3HNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle PFNGLCOLOR3HNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$763.PFNGLCOLOR3HNVPROC$FUNC, false
    );
}


