// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$294 {

    static final FunctionDescriptor PFNGLBINDTEXTUREUNITPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLBINDTEXTUREUNITPROC$MH = RuntimeHelper.downcallHandle(
        constants$294.PFNGLBINDTEXTUREUNITPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETTEXTUREIMAGEPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETTEXTUREIMAGEPROC$MH = RuntimeHelper.downcallHandle(
        constants$294.PFNGLGETTEXTUREIMAGEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC$MH = RuntimeHelper.downcallHandle(
        constants$294.PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC$FUNC, false
    );
}


