// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$737 {

    static final FunctionDescriptor PFNGLCLEARDEPTHDNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle PFNGLCLEARDEPTHDNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$737.PFNGLCLEARDEPTHDNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDEPTHBOUNDSDNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle PFNGLDEPTHBOUNDSDNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$737.PFNGLDEPTHBOUNDSDNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDRAWTEXTURENVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle PFNGLDRAWTEXTURENVPROC$MH = RuntimeHelper.downcallHandle(
        constants$737.PFNGLDRAWTEXTURENVPROC$FUNC, false
    );
}


