// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$199 {

    static final FunctionDescriptor PFNGLTEXCOORDP4UIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLTEXCOORDP4UIPROC$MH = RuntimeHelper.downcallHandle(
        constants$199.PFNGLTEXCOORDP4UIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXCOORDP4UIVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLTEXCOORDP4UIVPROC$MH = RuntimeHelper.downcallHandle(
        constants$199.PFNGLTEXCOORDP4UIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTITEXCOORDP1UIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLMULTITEXCOORDP1UIPROC$MH = RuntimeHelper.downcallHandle(
        constants$199.PFNGLMULTITEXCOORDP1UIPROC$FUNC, false
    );
}


