// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$245 {

    static final FunctionDescriptor PFNGLVERTEXATTRIBL3DVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBL3DVPROC$MH = RuntimeHelper.downcallHandle(
        constants$245.PFNGLVERTEXATTRIBL3DVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBL4DVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBL4DVPROC$MH = RuntimeHelper.downcallHandle(
        constants$245.PFNGLVERTEXATTRIBL4DVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBLPOINTERPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBLPOINTERPROC$MH = RuntimeHelper.downcallHandle(
        constants$245.PFNGLVERTEXATTRIBLPOINTERPROC$FUNC, false
    );
}


