// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$180 {

    static final FunctionDescriptor PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC$MH = RuntimeHelper.downcallHandle(
        constants$180.PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC$MH = RuntimeHelper.downcallHandle(
        constants$180.PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROVOKINGVERTEXPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLPROVOKINGVERTEXPROC$MH = RuntimeHelper.downcallHandle(
        constants$180.PFNGLPROVOKINGVERTEXPROC$FUNC, false
    );
}


