// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$566 {

    static final FunctionDescriptor PFNGLCOMPRESSEDTEXTURESUBIMAGE3DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLCOMPRESSEDTEXTURESUBIMAGE3DEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$566.PFNGLCOMPRESSEDTEXTURESUBIMAGE3DEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOMPRESSEDTEXTURESUBIMAGE2DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLCOMPRESSEDTEXTURESUBIMAGE2DEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$566.PFNGLCOMPRESSEDTEXTURESUBIMAGE2DEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOMPRESSEDTEXTURESUBIMAGE1DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLCOMPRESSEDTEXTURESUBIMAGE1DEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$566.PFNGLCOMPRESSEDTEXTURESUBIMAGE1DEXTPROC$FUNC, false
    );
}


