// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$415 {

    static final FunctionDescriptor PFNGLCLEARCOLORXOESPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLCLEARCOLORXOESPROC$MH = RuntimeHelper.downcallHandle(
        constants$415.PFNGLCLEARCOLORXOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCLEARDEPTHXOESPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLCLEARDEPTHXOESPROC$MH = RuntimeHelper.downcallHandle(
        constants$415.PFNGLCLEARDEPTHXOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCLIPPLANEXOESPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLCLIPPLANEXOESPROC$MH = RuntimeHelper.downcallHandle(
        constants$415.PFNGLCLIPPLANEXOESPROC$FUNC, false
    );
}


