// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$84 {

    static final FunctionDescriptor PFNGLMULTITEXCOORD2FARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle PFNGLMULTITEXCOORD2FARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$84.PFNGLMULTITEXCOORD2FARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTITEXCOORD2FVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLMULTITEXCOORD2FVARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$84.PFNGLMULTITEXCOORD2FVARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTITEXCOORD2IARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLMULTITEXCOORD2IARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$84.PFNGLMULTITEXCOORD2IARBPROC$FUNC, false
    );
}


