// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$462 {

    static final FunctionDescriptor PFNGLGETUNIFORMI64VNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETUNIFORMI64VNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$462.PFNGLGETUNIFORMI64VNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETUNIFORMUI64VNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETUNIFORMUI64VNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$462.PFNGLGETUNIFORMUI64VNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM1I64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM1I64NVPROC$MH = RuntimeHelper.downcallHandle(
        constants$462.PFNGLPROGRAMUNIFORM1I64NVPROC$FUNC, false
    );
}


