// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$497 {

    static final FunctionDescriptor PFNGLISOBJECTBUFFERATIPROC$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLISOBJECTBUFFERATIPROC$MH = RuntimeHelper.downcallHandle(
        constants$497.PFNGLISOBJECTBUFFERATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUPDATEOBJECTBUFFERATIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLUPDATEOBJECTBUFFERATIPROC$MH = RuntimeHelper.downcallHandle(
        constants$497.PFNGLUPDATEOBJECTBUFFERATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETOBJECTBUFFERFVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETOBJECTBUFFERFVATIPROC$MH = RuntimeHelper.downcallHandle(
        constants$497.PFNGLGETOBJECTBUFFERFVATIPROC$FUNC, false
    );
}


