// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$24 {

    static final FunctionDescriptor glColor4bv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glColor4bv$MH = RuntimeHelper.downcallHandle(
        "glColor4bv",
        constants$24.glColor4bv$FUNC, false
    );
    static final FunctionDescriptor glColor4dv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glColor4dv$MH = RuntimeHelper.downcallHandle(
        "glColor4dv",
        constants$24.glColor4dv$FUNC, false
    );
    static final FunctionDescriptor glColor4fv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glColor4fv$MH = RuntimeHelper.downcallHandle(
        "glColor4fv",
        constants$24.glColor4fv$FUNC, false
    );
    static final FunctionDescriptor glColor4iv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glColor4iv$MH = RuntimeHelper.downcallHandle(
        "glColor4iv",
        constants$24.glColor4iv$FUNC, false
    );
    static final FunctionDescriptor glColor4sv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glColor4sv$MH = RuntimeHelper.downcallHandle(
        "glColor4sv",
        constants$24.glColor4sv$FUNC, false
    );
    static final FunctionDescriptor glColor4ubv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glColor4ubv$MH = RuntimeHelper.downcallHandle(
        "glColor4ubv",
        constants$24.glColor4ubv$FUNC, false
    );
}


