// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$235 {

    static final FunctionDescriptor PFNGLPROGRAMUNIFORM4DPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM4DPROC$MH = RuntimeHelper.downcallHandle(
        constants$235.PFNGLPROGRAMUNIFORM4DPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM4DVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM4DVPROC$MH = RuntimeHelper.downcallHandle(
        constants$235.PFNGLPROGRAMUNIFORM4DVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM4UIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM4UIPROC$MH = RuntimeHelper.downcallHandle(
        constants$235.PFNGLPROGRAMUNIFORM4UIPROC$FUNC, false
    );
}


