// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$287 {

    static final FunctionDescriptor PFNGLTEXTURESTORAGE1DPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLTEXTURESTORAGE1DPROC$MH = RuntimeHelper.downcallHandle(
        constants$287.PFNGLTEXTURESTORAGE1DPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTURESTORAGE2DPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLTEXTURESTORAGE2DPROC$MH = RuntimeHelper.downcallHandle(
        constants$287.PFNGLTEXTURESTORAGE2DPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTURESTORAGE3DPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLTEXTURESTORAGE3DPROC$MH = RuntimeHelper.downcallHandle(
        constants$287.PFNGLTEXTURESTORAGE3DPROC$FUNC, false
    );
}


