// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$501 {

    static final FunctionDescriptor PFNGLGETVERTEXATTRIBARRAYOBJECTFVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETVERTEXATTRIBARRAYOBJECTFVATIPROC$MH = RuntimeHelper.downcallHandle(
        constants$501.PFNGLGETVERTEXATTRIBARRAYOBJECTFVATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETVERTEXATTRIBARRAYOBJECTIVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETVERTEXATTRIBARRAYOBJECTIVATIPROC$MH = RuntimeHelper.downcallHandle(
        constants$501.PFNGLGETVERTEXATTRIBARRAYOBJECTIVATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXSTREAM1SATIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXSTREAM1SATIPROC$MH = RuntimeHelper.downcallHandle(
        constants$501.PFNGLVERTEXSTREAM1SATIPROC$FUNC, false
    );
}


