// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$716 {

    static final FunctionDescriptor PFNGLWINDOWPOS3FVMESAPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLWINDOWPOS3FVMESAPROC$MH = RuntimeHelper.downcallHandle(
        constants$716.PFNGLWINDOWPOS3FVMESAPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLWINDOWPOS3IMESAPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLWINDOWPOS3IMESAPROC$MH = RuntimeHelper.downcallHandle(
        constants$716.PFNGLWINDOWPOS3IMESAPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLWINDOWPOS3IVMESAPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLWINDOWPOS3IVMESAPROC$MH = RuntimeHelper.downcallHandle(
        constants$716.PFNGLWINDOWPOS3IVMESAPROC$FUNC, false
    );
}


