// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$628 {

    static final FunctionDescriptor PFNGLGETRENDERBUFFERPARAMETERIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGETRENDERBUFFERPARAMETERIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$628.PFNGLGETRENDERBUFFERPARAMETERIVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISFRAMEBUFFEREXTPROC$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLISFRAMEBUFFEREXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$628.PFNGLISFRAMEBUFFEREXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBINDFRAMEBUFFEREXTPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLBINDFRAMEBUFFEREXTPROC$MH = RuntimeHelper.downcallHandle(
        constants$628.PFNGLBINDFRAMEBUFFEREXTPROC$FUNC, false
    );
}


