// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$746 {

    static final FunctionDescriptor PFNGLSETFENCENVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLSETFENCENVPROC$MH = RuntimeHelper.downcallHandle(
        constants$746.PFNGLSETFENCENVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFRAGMENTCOVERAGECOLORNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLFRAGMENTCOVERAGECOLORNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$746.PFNGLFRAGMENTCOVERAGECOLORNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMNAMEDPARAMETER4FNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle PFNGLPROGRAMNAMEDPARAMETER4FNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$746.PFNGLPROGRAMNAMEDPARAMETER4FNVPROC$FUNC, false
    );
}


