// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$897 {

    static final FunctionDescriptor PFNGLSPRITEPARAMETERIVSGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLSPRITEPARAMETERIVSGIXPROC$MH = RuntimeHelper.downcallHandle(
        constants$897.PFNGLSPRITEPARAMETERIVSGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTAGSAMPLEBUFFERSGIXPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLTAGSAMPLEBUFFERSGIXPROC$MH = RuntimeHelper.downcallHandle(
        constants$897.PFNGLTAGSAMPLEBUFFERSGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOLORTABLESGIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLCOLORTABLESGIPROC$MH = RuntimeHelper.downcallHandle(
        constants$897.PFNGLCOLORTABLESGIPROC$FUNC, false
    );
}


