// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$824 {

    static final FunctionDescriptor PFNGLGENTRANSFORMFEEDBACKSNVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLGENTRANSFORMFEEDBACKSNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$824.PFNGLGENTRANSFORMFEEDBACKSNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISTRANSFORMFEEDBACKNVPROC$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLISTRANSFORMFEEDBACKNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$824.PFNGLISTRANSFORMFEEDBACKNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPAUSETRANSFORMFEEDBACKNVPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLPAUSETRANSFORMFEEDBACKNVPROC$MH = RuntimeHelper.downcallHandle(
        constants$824.PFNGLPAUSETRANSFORMFEEDBACKNVPROC$FUNC, false
    );
}


