// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$193 {

    static final FunctionDescriptor PFNGLVERTEXATTRIBP2UIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBP2UIPROC$MH = RuntimeHelper.downcallHandle(
        constants$193.PFNGLVERTEXATTRIBP2UIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBP2UIVPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBP2UIVPROC$MH = RuntimeHelper.downcallHandle(
        constants$193.PFNGLVERTEXATTRIBP2UIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBP3UIPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLVERTEXATTRIBP3UIPROC$MH = RuntimeHelper.downcallHandle(
        constants$193.PFNGLVERTEXATTRIBP3UIPROC$FUNC, false
    );
}


