// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$90 {

    static final FunctionDescriptor PFNGLMULTITEXCOORD4IARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle PFNGLMULTITEXCOORD4IARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$90.PFNGLMULTITEXCOORD4IARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTITEXCOORD4IVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFNGLMULTITEXCOORD4IVARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$90.PFNGLMULTITEXCOORD4IVARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTITEXCOORD4SARBPROC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle PFNGLMULTITEXCOORD4SARBPROC$MH = RuntimeHelper.downcallHandle(
        constants$90.PFNGLMULTITEXCOORD4SARBPROC$FUNC, false
    );
}


