// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface glutButtonBoxFunc$callback {

    void apply(int x0, int x1);
    static NativeSymbol allocate(glutButtonBoxFunc$callback fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(glutButtonBoxFunc$callback.class, fi, constants$950.glutButtonBoxFunc$callback$FUNC, "(II)V", scope);
    }
    static glutButtonBoxFunc$callback ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("glutButtonBoxFunc$callback::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1) -> {
            try {
                constants$950.glutButtonBoxFunc$callback$MH.invokeExact(symbol, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


