// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLPROGRAMENVPARAMETER4FARBPROC {

    void apply(int x0, int x1, float x2, float x3, float x4, float x5);
    static NativeSymbol allocate(PFNGLPROGRAMENVPARAMETER4FARBPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLPROGRAMENVPARAMETER4FARBPROC.class, fi, constants$326.PFNGLPROGRAMENVPARAMETER4FARBPROC$FUNC, "(IIFFFF)V", scope);
    }
    static PFNGLPROGRAMENVPARAMETER4FARBPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLPROGRAMENVPARAMETER4FARBPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1, float x2, float x3, float x4, float x5) -> {
            try {
                constants$326.PFNGLPROGRAMENVPARAMETER4FARBPROC$MH.invokeExact(symbol, x0, x1, x2, x3, x4, x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


