// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC {

    void apply(int x0);
    static NativeSymbol allocate(PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC.class, fi, constants$691.PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC$FUNC, "(I)V", scope);
    }
    static PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0) -> {
            try {
                constants$691.PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


