// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLENDPERFMONITORAMDPROC {

    void apply(int x0);
    static NativeSymbol allocate(PFNGLENDPERFMONITORAMDPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLENDPERFMONITORAMDPROC.class, fi, constants$473.PFNGLENDPERFMONITORAMDPROC$FUNC, "(I)V", scope);
    }
    static PFNGLENDPERFMONITORAMDPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLENDPERFMONITORAMDPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0) -> {
            try {
                constants$473.PFNGLENDPERFMONITORAMDPROC$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


