// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLVERTEXATTRIBL3DPROC {

    void apply(int x0, double x1, double x2, double x3);
    static NativeSymbol allocate(PFNGLVERTEXATTRIBL3DPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLVERTEXATTRIBL3DPROC.class, fi, constants$243.PFNGLVERTEXATTRIBL3DPROC$FUNC, "(IDDD)V", scope);
    }
    static PFNGLVERTEXATTRIBL3DPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLVERTEXATTRIBL3DPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, double x1, double x2, double x3) -> {
            try {
                constants$243.PFNGLVERTEXATTRIBL3DPROC$MH.invokeExact(symbol, x0, x1, x2, x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


