// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLBINDBUFFEROFFSETEXTPROC {

    void apply(int x0, int x1, int x2, long x3);
    static NativeSymbol allocate(PFNGLBINDBUFFEROFFSETEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLBINDBUFFEROFFSETEXTPROC.class, fi, constants$675.PFNGLBINDBUFFEROFFSETEXTPROC$FUNC, "(IIIJ)V", scope);
    }
    static PFNGLBINDBUFFEROFFSETEXTPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLBINDBUFFEROFFSETEXTPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1, int x2, long x3) -> {
            try {
                constants$675.PFNGLBINDBUFFEROFFSETEXTPROC$MH.invokeExact(symbol, x0, x1, x2, x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


