// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLCOLOR4UBVERTEX2FSUNPROC {

    void apply(byte x0, byte x1, byte x2, byte x3, float x4, float x5);
    static NativeSymbol allocate(PFNGLCOLOR4UBVERTEX2FSUNPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLCOLOR4UBVERTEX2FSUNPROC.class, fi, constants$905.PFNGLCOLOR4UBVERTEX2FSUNPROC$FUNC, "(BBBBFF)V", scope);
    }
    static PFNGLCOLOR4UBVERTEX2FSUNPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLCOLOR4UBVERTEX2FSUNPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (byte x0, byte x1, byte x2, byte x3, float x4, float x5) -> {
            try {
                constants$905.PFNGLCOLOR4UBVERTEX2FSUNPROC$MH.invokeExact(symbol, x0, x1, x2, x3, x4, x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


