// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLSTARTINSTRUMENTSSGIXPROC {

    void apply();
    static NativeSymbol allocate(PFNGLSTARTINSTRUMENTSSGIXPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLSTARTINSTRUMENTSSGIXPROC.class, fi, constants$891.PFNGLSTARTINSTRUMENTSSGIXPROC$FUNC, "()V", scope);
    }
    static PFNGLSTARTINSTRUMENTSSGIXPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLSTARTINSTRUMENTSSGIXPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return () -> {
            try {
                constants$891.PFNGLSTARTINSTRUMENTSSGIXPROC$MH.invokeExact(symbol);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


