// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLPATHFOGGENNVPROC {

    void apply(int x0);
    static NativeSymbol allocate(PFNGLPATHFOGGENNVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLPATHFOGGENNVPROC.class, fi, constants$799.PFNGLPATHFOGGENNVPROC$FUNC, "(I)V", scope);
    }
    static PFNGLPATHFOGGENNVPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLPATHFOGGENNVPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0) -> {
            try {
                constants$799.PFNGLPATHFOGGENNVPROC$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


