// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLPROGRAMPARAMETER4DNVPROC {

    void apply(int x0, int x1, double x2, double x3, double x4, double x5);
    static NativeSymbol allocate(PFNGLPROGRAMPARAMETER4DNVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLPROGRAMPARAMETER4DNVPROC.class, fi, constants$845.PFNGLPROGRAMPARAMETER4DNVPROC$FUNC, "(IIDDDD)V", scope);
    }
    static PFNGLPROGRAMPARAMETER4DNVPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLPROGRAMPARAMETER4DNVPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1, double x2, double x3, double x4, double x5) -> {
            try {
                constants$845.PFNGLPROGRAMPARAMETER4DNVPROC$MH.invokeExact(symbol, x0, x1, x2, x3, x4, x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


