// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLBUFFERSTORAGEEXTERNALEXTPROC {

    void apply(int x0, long x1, long x2, jdk.incubator.foreign.MemoryAddress x3, int x4);
    static NativeSymbol allocate(PFNGLBUFFERSTORAGEEXTERNALEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLBUFFERSTORAGEEXTERNALEXTPROC.class, fi, constants$623.PFNGLBUFFERSTORAGEEXTERNALEXTPROC$FUNC, "(IJJLjdk/incubator/foreign/MemoryAddress;I)V", scope);
    }
    static PFNGLBUFFERSTORAGEEXTERNALEXTPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLBUFFERSTORAGEEXTERNALEXTPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, long x1, long x2, jdk.incubator.foreign.MemoryAddress x3, int x4) -> {
            try {
                constants$623.PFNGLBUFFERSTORAGEEXTERNALEXTPROC$MH.invokeExact(symbol, x0, x1, x2, (jdk.incubator.foreign.Addressable)x3, x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


