// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLTEXCOORD2FVERTEX3FSUNPROC {

    void apply(float x0, float x1, float x2, float x3, float x4);
    static NativeSymbol allocate(PFNGLTEXCOORD2FVERTEX3FSUNPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLTEXCOORD2FVERTEX3FSUNPROC.class, fi, constants$909.PFNGLTEXCOORD2FVERTEX3FSUNPROC$FUNC, "(FFFFF)V", scope);
    }
    static PFNGLTEXCOORD2FVERTEX3FSUNPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLTEXCOORD2FVERTEX3FSUNPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (float x0, float x1, float x2, float x3, float x4) -> {
            try {
                constants$909.PFNGLTEXCOORD2FVERTEX3FSUNPROC$MH.invokeExact(symbol, x0, x1, x2, x3, x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


