// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLPIXELZOOMXOESPROC {

    void apply(int x0, int x1);
    static NativeSymbol allocate(PFNGLPIXELZOOMXOESPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLPIXELZOOMXOESPROC.class, fi, constants$440.PFNGLPIXELZOOMXOESPROC$FUNC, "(II)V", scope);
    }
    static PFNGLPIXELZOOMXOESPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLPIXELZOOMXOESPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1) -> {
            try {
                constants$440.PFNGLPIXELZOOMXOESPROC$MH.invokeExact(symbol, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


