// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLBINORMAL3DEXTPROC {

    void apply(double x0, double x1, double x2);
    static NativeSymbol allocate(PFNGLBINORMAL3DEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLBINORMAL3DEXTPROC.class, fi, constants$529.PFNGLBINORMAL3DEXTPROC$FUNC, "(DDD)V", scope);
    }
    static PFNGLBINORMAL3DEXTPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLBINORMAL3DEXTPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (double x0, double x1, double x2) -> {
            try {
                constants$529.PFNGLBINORMAL3DEXTPROC$MH.invokeExact(symbol, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


