// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLSECONDARYCOLOR3FPROC {

    void apply(float x0, float x1, float x2);
    static NativeSymbol allocate(PFNGLSECONDARYCOLOR3FPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLSECONDARYCOLOR3FPROC.class, fi, constants$96.PFNGLSECONDARYCOLOR3FPROC$FUNC, "(FFF)V", scope);
    }
    static PFNGLSECONDARYCOLOR3FPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLSECONDARYCOLOR3FPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (float x0, float x1, float x2) -> {
            try {
                constants$96.PFNGLSECONDARYCOLOR3FPROC$MH.invokeExact(symbol, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


