// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLFRAGMENTCOVERAGECOLORNVPROC {

    void apply(int x0);
    static NativeSymbol allocate(PFNGLFRAGMENTCOVERAGECOLORNVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLFRAGMENTCOVERAGECOLORNVPROC.class, fi, constants$746.PFNGLFRAGMENTCOVERAGECOLORNVPROC$FUNC, "(I)V", scope);
    }
    static PFNGLFRAGMENTCOVERAGECOLORNVPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLFRAGMENTCOVERAGECOLORNVPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0) -> {
            try {
                constants$746.PFNGLFRAGMENTCOVERAGECOLORNVPROC$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


