// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLPROGRAMLOCALPARAMETER4DARBPROC {

    void apply(int x0, int x1, double x2, double x3, double x4, double x5);
    static NativeSymbol allocate(PFNGLPROGRAMLOCALPARAMETER4DARBPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLPROGRAMLOCALPARAMETER4DARBPROC.class, fi, constants$326.PFNGLPROGRAMLOCALPARAMETER4DARBPROC$FUNC, "(IIDDDD)V", scope);
    }
    static PFNGLPROGRAMLOCALPARAMETER4DARBPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLPROGRAMLOCALPARAMETER4DARBPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1, double x2, double x3, double x4, double x5) -> {
            try {
                constants$326.PFNGLPROGRAMLOCALPARAMETER4DARBPROC$MH.invokeExact(symbol, x0, x1, x2, x3, x4, x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


