// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLTEXTUREPARAMETERFPROC {

    void apply(int x0, int x1, float x2);
    static NativeSymbol allocate(PFNGLTEXTUREPARAMETERFPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLTEXTUREPARAMETERFPROC.class, fi, constants$291.PFNGLTEXTUREPARAMETERFPROC$FUNC, "(IIF)V", scope);
    }
    static PFNGLTEXTUREPARAMETERFPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLTEXTUREPARAMETERFPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1, float x2) -> {
            try {
                constants$291.PFNGLTEXTUREPARAMETERFPROC$MH.invokeExact(symbol, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


