// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLBINDVERTEXARRAYAPPLEPROC {

    void apply(int x0);
    static NativeSymbol allocate(PFNGLBINDVERTEXARRAYAPPLEPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLBINDVERTEXARRAYAPPLEPROC.class, fi, constants$482.PFNGLBINDVERTEXARRAYAPPLEPROC$FUNC, "(I)V", scope);
    }
    static PFNGLBINDVERTEXARRAYAPPLEPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLBINDVERTEXARRAYAPPLEPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0) -> {
            try {
                constants$482.PFNGLBINDVERTEXARRAYAPPLEPROC$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


