// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLLGPUNAMEDBUFFERSUBDATANVXPROC {

    void apply(int x0, int x1, long x2, long x3, jdk.incubator.foreign.MemoryAddress x4);
    static NativeSymbol allocate(PFNGLLGPUNAMEDBUFFERSUBDATANVXPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLLGPUNAMEDBUFFERSUBDATANVXPROC.class, fi, constants$721.PFNGLLGPUNAMEDBUFFERSUBDATANVXPROC$FUNC, "(IIJJLjdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static PFNGLLGPUNAMEDBUFFERSUBDATANVXPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLLGPUNAMEDBUFFERSUBDATANVXPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1, long x2, long x3, jdk.incubator.foreign.MemoryAddress x4) -> {
            try {
                constants$721.PFNGLLGPUNAMEDBUFFERSUBDATANVXPROC$MH.invokeExact(symbol, x0, x1, x2, x3, (jdk.incubator.foreign.Addressable)x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


