// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLUSEPROGRAMOBJECTARBPROC {

    void apply(int x0);
    static NativeSymbol allocate(PFNGLUSEPROGRAMOBJECTARBPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLUSEPROGRAMOBJECTARBPROC.class, fi, constants$361.PFNGLUSEPROGRAMOBJECTARBPROC$FUNC, "(I)V", scope);
    }
    static PFNGLUSEPROGRAMOBJECTARBPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLUSEPROGRAMOBJECTARBPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0) -> {
            try {
                constants$361.PFNGLUSEPROGRAMOBJECTARBPROC$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


