// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLSAMPLEMAPATIPROC {

    void apply(int x0, int x1, int x2);
    static NativeSymbol allocate(PFNGLSAMPLEMAPATIPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLSAMPLEMAPATIPROC.class, fi, constants$492.PFNGLSAMPLEMAPATIPROC$FUNC, "(III)V", scope);
    }
    static PFNGLSAMPLEMAPATIPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLSAMPLEMAPATIPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1, int x2) -> {
            try {
                constants$492.PFNGLSAMPLEMAPATIPROC$MH.invokeExact(symbol, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


