// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLVERTEXATTRIBFORMATNVPROC {

    void apply(int x0, int x1, int x2, byte x3, int x4);
    static NativeSymbol allocate(PFNGLVERTEXATTRIBFORMATNVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLVERTEXATTRIBFORMATNVPROC.class, fi, constants$839.PFNGLVERTEXATTRIBFORMATNVPROC$FUNC, "(IIIBI)V", scope);
    }
    static PFNGLVERTEXATTRIBFORMATNVPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLVERTEXATTRIBFORMATNVPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1, int x2, byte x3, int x4) -> {
            try {
                constants$839.PFNGLVERTEXATTRIBFORMATNVPROC$MH.invokeExact(symbol, x0, x1, x2, x3, x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


