// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLGENERATEMIPMAPEXTPROC {

    void apply(int x0);
    static NativeSymbol allocate(PFNGLGENERATEMIPMAPEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLGENERATEMIPMAPEXTPROC.class, fi, constants$631.PFNGLGENERATEMIPMAPEXTPROC$FUNC, "(I)V", scope);
    }
    static PFNGLGENERATEMIPMAPEXTPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLGENERATEMIPMAPEXTPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0) -> {
            try {
                constants$631.PFNGLGENERATEMIPMAPEXTPROC$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


