// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLMEMORYBARRIERBYREGIONPROC {

    void apply(int x0);
    static NativeSymbol allocate(PFNGLMEMORYBARRIERBYREGIONPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLMEMORYBARRIERBYREGIONPROC.class, fi, constants$304.PFNGLMEMORYBARRIERBYREGIONPROC$FUNC, "(I)V", scope);
    }
    static PFNGLMEMORYBARRIERBYREGIONPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLMEMORYBARRIERBYREGIONPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0) -> {
            try {
                constants$304.PFNGLMEMORYBARRIERBYREGIONPROC$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


