// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC {

    void apply(int x0, long x1, long x2);
    static NativeSymbol allocate(PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC.class, fi, constants$277.PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC$FUNC, "(IJJ)V", scope);
    }
    static PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, long x1, long x2) -> {
            try {
                constants$277.PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC$MH.invokeExact(symbol, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


