// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLAPPLYTEXTUREEXTPROC {

    void apply(int x0);
    static NativeSymbol allocate(PFNGLAPPLYTEXTUREEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLAPPLYTEXTUREEXTPROC.class, fi, constants$640.PFNGLAPPLYTEXTUREEXTPROC$FUNC, "(I)V", scope);
    }
    static PFNGLAPPLYTEXTUREEXTPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLAPPLYTEXTUREEXTPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0) -> {
            try {
                constants$640.PFNGLAPPLYTEXTUREEXTPROC$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


