// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLGETCOMMANDHEADERNVPROC {

    int apply(int x0, int x1);
    static NativeSymbol allocate(PFNGLGETCOMMANDHEADERNVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLGETCOMMANDHEADERNVPROC.class, fi, constants$730.PFNGLGETCOMMANDHEADERNVPROC$FUNC, "(II)I", scope);
    }
    static PFNGLGETCOMMANDHEADERNVPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLGETCOMMANDHEADERNVPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1) -> {
            try {
                return (int)constants$730.PFNGLGETCOMMANDHEADERNVPROC$MH.invokeExact(symbol, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


