// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLISBUFFERRESIDENTNVPROC {

    byte apply(int x0);
    static NativeSymbol allocate(PFNGLISBUFFERRESIDENTNVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLISBUFFERRESIDENTNVPROC.class, fi, constants$813.PFNGLISBUFFERRESIDENTNVPROC$FUNC, "(I)B", scope);
    }
    static PFNGLISBUFFERRESIDENTNVPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLISBUFFERRESIDENTNVPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0) -> {
            try {
                return (byte)constants$813.PFNGLISBUFFERRESIDENTNVPROC$MH.invokeExact(symbol, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


