// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLMULTITEXCOORD2BOESPROC {

    void apply(int x0, byte x1, byte x2);
    static NativeSymbol allocate(PFNGLMULTITEXCOORD2BOESPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLMULTITEXCOORD2BOESPROC.class, fi, constants$408.PFNGLMULTITEXCOORD2BOESPROC$FUNC, "(IBB)V", scope);
    }
    static PFNGLMULTITEXCOORD2BOESPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLMULTITEXCOORD2BOESPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, byte x1, byte x2) -> {
            try {
                constants$408.PFNGLMULTITEXCOORD2BOESPROC$MH.invokeExact(symbol, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


