// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLVERTEXATTRIB4FNVPROC {

    void apply(int x0, float x1, float x2, float x3, float x4);
    static NativeSymbol allocate(PFNGLVERTEXATTRIB4FNVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLVERTEXATTRIB4FNVPROC.class, fi, constants$855.PFNGLVERTEXATTRIB4FNVPROC$FUNC, "(IFFFF)V", scope);
    }
    static PFNGLVERTEXATTRIB4FNVPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLVERTEXATTRIB4FNVPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, float x1, float x2, float x3, float x4) -> {
            try {
                constants$855.PFNGLVERTEXATTRIB4FNVPROC$MH.invokeExact(symbol, x0, x1, x2, x3, x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


