// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLENDTRANSFORMFEEDBACKEXTPROC {

    void apply();
    static NativeSymbol allocate(PFNGLENDTRANSFORMFEEDBACKEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLENDTRANSFORMFEEDBACKEXTPROC.class, fi, constants$674.PFNGLENDTRANSFORMFEEDBACKEXTPROC$FUNC, "()V", scope);
    }
    static PFNGLENDTRANSFORMFEEDBACKEXTPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLENDTRANSFORMFEEDBACKEXTPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return () -> {
            try {
                constants$674.PFNGLENDTRANSFORMFEEDBACKEXTPROC$MH.invokeExact(symbol);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


