// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLGETHISTOGRAMEXTPROC {

    void apply(int x0, byte x1, int x2, int x3, jdk.incubator.foreign.MemoryAddress x4);
    static NativeSymbol allocate(PFNGLGETHISTOGRAMEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLGETHISTOGRAMEXTPROC.class, fi, constants$636.PFNGLGETHISTOGRAMEXTPROC$FUNC, "(IBIILjdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static PFNGLGETHISTOGRAMEXTPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLGETHISTOGRAMEXTPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, byte x1, int x2, int x3, jdk.incubator.foreign.MemoryAddress x4) -> {
            try {
                constants$636.PFNGLGETHISTOGRAMEXTPROC$MH.invokeExact(symbol, x0, x1, x2, x3, (jdk.incubator.foreign.Addressable)x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


