// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLISENABLEDIPROC {

    byte apply(int x0, int x1);
    static NativeSymbol allocate(PFNGLISENABLEDIPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLISENABLEDIPROC.class, fi, constants$148.PFNGLISENABLEDIPROC$FUNC, "(II)B", scope);
    }
    static PFNGLISENABLEDIPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLISENABLEDIPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, int x1) -> {
            try {
                return (byte)constants$148.PFNGLISENABLEDIPROC$MH.invokeExact(symbol, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


