// Generated by jextract

package org.eclipse.swt.opengl.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface PFNGLSECONDARYCOLOR3BEXTPROC {

    void apply(byte x0, byte x1, byte x2);
    static NativeSymbol allocate(PFNGLSECONDARYCOLOR3BEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLSECONDARYCOLOR3BEXTPROC.class, fi, constants$655.PFNGLSECONDARYCOLOR3BEXTPROC$FUNC, "(BBB)V", scope);
    }
    static PFNGLSECONDARYCOLOR3BEXTPROC ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("PFNGLSECONDARYCOLOR3BEXTPROC::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (byte x0, byte x1, byte x2) -> {
            try {
                constants$655.PFNGLSECONDARYCOLOR3BEXTPROC$MH.invokeExact(symbol, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


