# This workflow will build the GTK4 part of SWT to check it compiles

name: GTK4 Build
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        config: 
          - { name: Linux, os: ubuntu-latest, native: gtk.linux.x86_64 }
    name: Verify ${{ matrix.config.name }} with Java-${{ matrix.java }}
    steps:
    - name: checkout swt
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
       fetch-depth: 0 # required for jgit timestamp provider to work
       lfs: false # lfs-pull is not necessary, the natives are re-build in each run
    - name: Install Linux requirements
      run: |
        sudo apt-get update -qq 
        sudo apt-get install -qq -y libgtk-4-dev libgtk-3-dev freeglut3-dev webkit2gtk-driver
      if: ${{ matrix.config.native == 'gtk.linux.x86_64'}}
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.6
    - name: Build with Maven
      uses: coactions/setup-xvfb@6b00cf1889f4e1d5a48635647013c0508128ee1a
      with:
       working-directory: binaries/org.eclipse.swt.gtk.linux.x86_64
       run: >-
        mvn --batch-mode -V -U -e -ntp
        -Dnative=${{ matrix.config.native }}
        clean antrun:run@build-native-binaries

